package cz.cvut.fit.umati.ui.composite;

import org.springframework.context.annotation.Scope;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;

@org.springframework.stereotype.Component
@Scope("session")
public class MainToolbar extends CustomComponent {
	@AutoGenerated
	private HorizontalLayout mainLayout;

	@AutoGenerated
	private Link logoutLink;

	@AutoGenerated
	private Label loggedUser;

	@AutoGenerated
	private Label applicationTitle;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public MainToolbar() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
	}

	/*
	 * Getters
	 */
	public Label getLoggedUser() {
		return loggedUser;
	}

	public Link getLogoutLink() {
		return logoutLink;
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// applicationTitle
		applicationTitle = new Label();
		applicationTitle.setImmediate(false);
		applicationTitle.setWidth("-1px");
		applicationTitle.setHeight("-1px");
		applicationTitle.setValue("<H1>Umati Chanzo</H1>");
		applicationTitle.setContentMode(3);
		mainLayout.addComponent(applicationTitle);
		mainLayout.setExpandRatio(applicationTitle, 1.0f);
		
		// loggedUser
		loggedUser = new Label();
		loggedUser.setImmediate(false);
		loggedUser.setWidth("-1px");
		loggedUser.setHeight("-1px");
		loggedUser.setValue("not logged");
		mainLayout.addComponent(loggedUser);
		
		// logoutLink
		logoutLink = new Link();
		logoutLink.setCaption("Log Out");
		logoutLink.setImmediate(false);
		logoutLink.setDescription("Log Out");
		logoutLink.setWidth("-1px");
		logoutLink.setHeight("-1px");
		mainLayout.addComponent(logoutLink);
		
		return mainLayout;
	}
}
