package cz.cvut.fit.umati.ui.composite;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.Select;
import com.vaadin.ui.TextField;
import com.vaadin.ui.Button.ClickEvent;

import cz.cvut.fit.umati.FreeBaseUtil;
import cz.cvut.fit.umati.constants.XmlDataType;
import cz.cvut.fit.umati.model.SemanticAnnotation;

@org.springframework.stereotype.Component
@org.springframework.context.annotation.Scope("session")
public class ParameterQueryQuestion extends CustomComponent {
	@AutoGenerated
	private GridLayout mainLayout;

	@AutoGenerated
	private ListSelect parameterAnnotation;

	@AutoGenerated
	private HorizontalLayout searchLayout;

	@AutoGenerated
	private Button searchButton;

	@AutoGenerated
	private TextField searchField;

	@AutoGenerated
	private Label parameterAnnotationLabel;

	@AutoGenerated
	private ComboBox parameterType;

	@AutoGenerated
	private Label parameterTypeLabel;

	@AutoGenerated
	private TextField parameterField;

	@AutoGenerated
	private Label parameterLabel;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private static final long serialVersionUID = 1L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public ParameterQueryQuestion() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		
		// Parameter Type
		BeanItemContainer<XmlDataType> xmlDataTypeContainer = new BeanItemContainer<XmlDataType>(XmlDataType.class);
		xmlDataTypeContainer.addAll(Arrays.asList(XmlDataType.values()));
		parameterType.setContainerDataSource(xmlDataTypeContainer);

		// Search Button
		searchButton.addListener(new ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				BeanItemContainer<SemanticAnnotation> annotationContainer = new BeanItemContainer<SemanticAnnotation>(SemanticAnnotation.class);
				parameterAnnotation.setPropertyDataSource(null); // This is necessary, otherwise it's cleaning value!
				parameterAnnotation.setContainerDataSource(annotationContainer);
				parameterAnnotation.setItemCaptionMode(Select.ITEM_CAPTION_MODE_ID);
				parameterAnnotation.setItemCaptionPropertyId("name");
				
				Map<String, Object> result = FreeBaseUtil.query((String) searchField.getValue());
				@SuppressWarnings("unchecked")
				List<Object> data = (ArrayList<Object>) result.get("result");
				for (Object value : data) {
					@SuppressWarnings("unchecked")
					Map<String, Object> object = (Map<String, Object>) value;

					//TODO: tohle mapovani vyresit jinak!!!
					SemanticAnnotation semanticAnnotation = new SemanticAnnotation();
					semanticAnnotation.setMid((String) object.get("mid"));
					semanticAnnotation.setId((String) object.get("id"));
					semanticAnnotation.setName((String) object.get("name"));
					//semanticAnnotation.setNotable(notable) (object.get("id"));
					semanticAnnotation.setLang((String) object.get("lang"));
					semanticAnnotation.setScore((double) object.get("score"));
					annotationContainer.addItem(semanticAnnotation);
					
					System.out.println("SemanticAnnotation: " + semanticAnnotation);
				}
			}
		});
	}

	@AutoGenerated
	private GridLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new GridLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("-1px");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		mainLayout.setColumns(2);
		mainLayout.setRows(4);

		// top-level component properties
		setWidth("-1px");
		setHeight("-1px");

		// parameterLabel
		parameterLabel = new Label();
		parameterLabel.setImmediate(false);
		parameterLabel.setWidth("-1px");
		parameterLabel.setHeight("-1px");
		parameterLabel.setValue("Parameter");
		mainLayout.addComponent(parameterLabel, 0, 0);
		mainLayout.setComponentAlignment(parameterLabel, new Alignment(6));

		// parameterField
		parameterField = new TextField();
		parameterField.setImmediate(false);
		parameterField.setWidth("-1px");
		parameterField.setHeight("-1px");
		parameterField.setNullRepresentation("");
		mainLayout.addComponent(parameterField, 1, 0);

		// parameterTypeLabel
		parameterTypeLabel = new Label();
		parameterTypeLabel.setImmediate(false);
		parameterTypeLabel.setWidth("-1px");
		parameterTypeLabel.setHeight("-1px");
		parameterTypeLabel.setValue("Parameter Type");
		mainLayout.addComponent(parameterTypeLabel, 0, 1);
		mainLayout.setComponentAlignment(parameterTypeLabel, new Alignment(6));

		// parameterType
		parameterType = new ComboBox();
		parameterType.setImmediate(false);
		parameterType.setWidth("-1px");
		parameterType.setHeight("-1px");
		mainLayout.addComponent(parameterType, 1, 1);

		// parameterAnnotationLabel
		parameterAnnotationLabel = new Label();
		parameterAnnotationLabel.setImmediate(false);
		parameterAnnotationLabel.setWidth("-1px");
		parameterAnnotationLabel.setHeight("-1px");
		parameterAnnotationLabel.setValue("Semantic Annotation");
		mainLayout.addComponent(parameterAnnotationLabel, 0, 2);
		mainLayout.setComponentAlignment(parameterAnnotationLabel, new Alignment(6));

		// searchLayout
		searchLayout = buildSearchLayout();
		mainLayout.addComponent(searchLayout, 1, 2);

		// parameterAnnotation
		parameterAnnotation = new ListSelect();
		parameterAnnotation.setImmediate(false);
		parameterAnnotation.setWidth("100.0%");
		parameterAnnotation.setHeight("-1px");
		mainLayout.addComponent(parameterAnnotation, 1, 3);

		return mainLayout;
	}

	@AutoGenerated
	private HorizontalLayout buildSearchLayout() {
		// common part: create layout
		searchLayout = new HorizontalLayout();
		searchLayout.setImmediate(false);
		searchLayout.setWidth("-1px");
		searchLayout.setHeight("-1px");
		searchLayout.setMargin(false);

		// searchField
		searchField = new TextField();
		searchField.setImmediate(false);
		searchField.setWidth("-1px");
		searchField.setHeight("-1px");
		searchField.setNullRepresentation("");
		searchLayout.addComponent(searchField);

		// searchButton
		searchButton = new Button();
		searchButton.setCaption("Search");
		searchButton.setImmediate(true);
		searchButton.setWidth("-1px");
		searchButton.setHeight("-1px");
		searchLayout.addComponent(searchButton);

		return searchLayout;
	}
}
